config/routes.rb
Lcbo::Application.routes.draw do
  root :to => "products#index"

  resources :products
  resources :stores

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	require 'open-uri'

	def index
		products_json = open("http://lcboapi.com/products?page=10").read
		@products = JSON.parse(products_json)
	end

	def show
		products_json = open("http://lcboapi.com/products/#{params[:id]}").read
		@products = JSON.parse(products_json)
		@product = @products['result']
	end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
	require 'open-uri'

	def index
		stores_json = open("http://lcboapi.com/stores").read
		@stores = JSON.parse(stores_json)
	end

	def show
		stores_json = open("http://lcboapi.com/stores/#{params[:id]}").read
		@stores = JSON.parse(stores_json)
		@store = @stores['result']
	end


end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/stores_helper.rb
module StoresHelper

	def convert_store_hours(time)
 		 hour = time.to_i / 60
 		 mins = time.to_i % 60
 		 return hour.to_s + ":" + mins.to_s + "0"
			
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome to LCBO</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
</body>
</html>

app/views/products/index.html.erb
<h1><img src="http://georgianwinetours.ca/support/images/lcbo_logo.jpg" alt="100" height="100" width="100"/></h1>
<p style="text-align:center"><%= link_to "Stores", stores_path %></p>

<% @products['result'].each do |product| %>
	<section>
		<p><%= link_to product['name'], product_path(product['id']) %></p>
		
	</section>
<% end %>

app/views/products/show.html.erb
<p><b><%= @product['name'] %></b></p>
<img src="<%= @product['image_thumb_url'] %>"/>
<li>Price: $<%= sprintf("%.2f", @product['price_in_cents'].to_f/100) %></li>
<li>Category: <%= @product['primary_category'] %></li>
<li>Alcohol Content: <%= @product['alcohol_content'].to_f/100 %>%</li>
<li>Inventory: <%= @product['inventory_count'].to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse %></li>

app/views/stores/index.html.erb
<h1>STORES</h1>

<p style="text-align:center"><%= link_to "Back", products_path %></p>

<% @stores['result'].each do |store| %>
	<section>
		<p><%= link_to store['name'], store_path(store['id']) %> - <%= store['city'] %></p>
	
	</section>
<% end %>

app/views/stores/show.html.erb
<p><b>LCBO (<%= @store['name'] %>)</b></p>
<p><%= @store['address_line_1'] %></p>
<p><%= @store['address_line_2'] %></p>
<p><%= @store['city'] %>, Ontario</p> 
<p><%= @store['province'] %></p>
<p><%= @store['postal_code'] %></p>
<p>Phone: <%= @store['telephone'] %></p><br>

</br><p>Wheelchair Access: <% if @store['has_wheelchair_accessability'] %>
						<%= 'Yes' %>
						<% else %>
						<%= 'No' %>
						<% end %>
						</p>
<p>Parking: <% if @store['has_parking']  %>
				<%= 'Yes' %>
				<% else %>
				<%= 'No' %>
				<% end %>
				</p>
<p>French services: <% if @store['has_bilingual_services']  %>
				<%= 'Yes' %>
				<% else %>
				<%= 'No' %>
				<% end %>
				</p><br>
</br><p>Hours:</p>
<p>Sunday: <%= convert_store_hours(@store['sunday_open']) %> - <%= convert_store_hours(@store['sunday_close']) %></p>
<p>Monday: <%= convert_store_hours (@store['monday_open']) %> - <%= convert_store_hours(@store['monday_close']) %></p>
<p>Tuesday: <%= convert_store_hours(@store['tuesday_open']) %> - <%= convert_store_hours(@store['tuesday_close']) %></p>
<p>Wednesday: <%= convert_store_hours(@store['wednesday_open']) %> - <%= convert_store_hours(@store['wednesday_close']) %></p>
<p>Thursday: <%= convert_store_hours(@store['thursday_open']) %> - <%= convert_store_hours(@store['thursday_close']) %></p>
<p>Friday: <%= convert_store_hours(@store['friday_open']) %> - <%= convert_store_hours(@store['friday_close']) %></p>
<p>Saturday <%= convert_store_hours(@store['saturday_open']) %> - <%= convert_store_hours(@store['saturday_close']) %></p>